export const EXPLORE_SOURCE_TOPICS = {
  "ai-agents": "AI & agents",
  "data-infrastructure": "Data & infrastructure",
  payments: "Payments",
  "creator-research": "Creators & research",
} as const;

export type ExploreSourceTopic = keyof typeof EXPLORE_SOURCE_TOPICS;

export interface ExploreSource {
  id: string;
  name: string;
  url: string;
  description: string;
  topic: ExploreSourceTopic;
  tags: string[];
}

/** Publisher links for browsing only. These entries contain no retained reading or payment authority. */
export const EXPLORE_SOURCES: readonly ExploreSource[] = [
  { id: "explore:openai-news", name: "OpenAI News", url: "https://openai.com/news/",
    description: "OpenAI research, product announcements and safety publications.", topic: "ai-agents", tags: ["OpenAI", "LLM", "research", "safety"] },
  { id: "explore:openai-developers", name: "OpenAI Developers", url: "https://developers.openai.com/",
    description: "Developer guides, API resources and examples from OpenAI.", topic: "ai-agents", tags: ["OpenAI", "API", "agents", "evaluation"] },
  { id: "explore:anthropic", name: "Anthropic", url: "https://www.anthropic.com/news",
    description: "Anthropic announcements and publications about Claude and AI systems.", topic: "ai-agents", tags: ["Anthropic", "Claude", "LLM", "safety"] },
  { id: "explore:deepmind", name: "Google DeepMind", url: "https://deepmind.google/blog/",
    description: "Research and model announcements from Google DeepMind.", topic: "ai-agents", tags: ["DeepMind", "research", "models", "AI"] },
  { id: "explore:google-research", name: "Google Research", url: "https://research.google/blog/",
    description: "Google Research publications on machine learning, computing and scientific research.", topic: "ai-agents", tags: ["Google", "research", "machine learning", "evaluation"] },
  { id: "explore:hugging-face", name: "Hugging Face", url: "https://huggingface.co/blog",
    description: "Writing about open models, datasets and machine learning tools on Hugging Face.", topic: "ai-agents", tags: ["open models", "datasets", "transformers", "agents"] },
  { id: "explore:langchain", name: "LangChain", url: "https://blog.langchain.com/",
    description: "LangChain and LangGraph engineering, agent workflows and evaluation guides.", topic: "ai-agents", tags: ["LangChain", "LangGraph", "agents", "evaluation"] },
  { id: "explore:llamaindex", name: "LlamaIndex", url: "https://www.llamaindex.ai/blog",
    description: "LlamaIndex writing on retrieval, document processing and agent workflows.", topic: "ai-agents", tags: ["LlamaIndex", "RAG", "retrieval", "agents"] },
  { id: "explore:pydantic-ai", name: "Pydantic AI", url: "https://ai.pydantic.dev/",
    description: "Pydantic AI documentation for typed agents, tools and model integrations.", topic: "ai-agents", tags: ["Python", "Pydantic", "agents", "tools"] },
  { id: "explore:ollama", name: "Ollama", url: "https://ollama.com/blog",
    description: "Ollama announcements and guides for running and using language models.", topic: "ai-agents", tags: ["Ollama", "local models", "LLM", "tools"] },
  { id: "explore:vllm", name: "vLLM", url: "https://vllm.ai/blog",
    description: "vLLM engineering and announcements about language model serving.", topic: "ai-agents", tags: ["vLLM", "inference", "serving", "performance"] },
  { id: "explore:gemini-api", name: "Gemini API", url: "https://ai.google.dev/gemini-api/docs",
    description: "Google documentation for Gemini API models, tools and integrations.", topic: "ai-agents", tags: ["Google", "Gemini", "API", "agents"] },
  { id: "explore:simon-willison", name: "Simon Willison", url: "https://simonwillison.net/",
    description: "Independent writing and experiments on language models, tools and data.", topic: "ai-agents", tags: ["LLM", "tools", "data", "AI engineering"] },
  { id: "explore:eugene-yan", name: "Eugene Yan", url: "https://eugeneyan.com/",
    description: "Independent writing on applied machine learning, evaluation and recommendation systems.", topic: "ai-agents", tags: ["machine learning", "evaluation", "recommendations", "AI engineering"] },
  { id: "explore:hamel-husain", name: "Hamel Husain", url: "https://hamel.dev/",
    description: "Independent practical writing about AI evaluation and machine learning systems.", topic: "ai-agents", tags: ["evaluation", "LLM", "machine learning", "AI engineering"] },
  { id: "explore:sebastian-raschka", name: "Sebastian Raschka", url: "https://sebastianraschka.com/blog/",
    description: "Independent technical writing on machine learning and language models.", topic: "ai-agents", tags: ["machine learning", "LLM", "research", "training"] },
  { id: "explore:chip-huyen", name: "Chip Huyen", url: "https://huyenchip.com/",
    description: "Independent writing on AI engineering and production machine learning.", topic: "ai-agents", tags: ["AI engineering", "agents", "machine learning", "evaluation"] },
  { id: "explore:lilian-weng", name: "Lilian Weng", url: "https://lilianweng.github.io/",
    description: "Independent technical explanations of language models and machine learning research.", topic: "ai-agents", tags: ["LLM", "agents", "research", "evaluation"] },
  { id: "explore:vicki-boykis", name: "Vicki Boykis", url: "https://vickiboykis.com/",
    description: "Independent writing about machine learning engineering, AI and data systems.", topic: "ai-agents", tags: ["machine learning", "AI engineering", "data systems", "infrastructure"] },
  { id: "explore:microsoft-research", name: "Microsoft Research", url: "https://www.microsoft.com/en-us/research/blog/",
    description: "Microsoft Research publications about AI, computing and scientific work.", topic: "ai-agents", tags: ["Microsoft", "research", "AI", "computing"] },
  { id: "explore:pytorch", name: "PyTorch", url: "https://pytorch.org/blog/",
    description: "PyTorch project and ecosystem writing on training, inference and machine learning tools.", topic: "ai-agents", tags: ["PyTorch", "training", "inference", "machine learning"] },

  { id: "explore:postgresql", name: "PostgreSQL", url: "https://www.postgresql.org/",
    description: "PostgreSQL documentation, release information and community news.", topic: "data-infrastructure", tags: ["PostgreSQL", "SQL", "databases", "queues"] },
  { id: "explore:sqlite", name: "SQLite", url: "https://www.sqlite.org/docs.html",
    description: "SQLite documentation on databases, transactions, backups and deployment.", topic: "data-infrastructure", tags: ["SQLite", "SQL", "databases", "backups"] },
  { id: "explore:nodejs", name: "Node.js", url: "https://nodejs.org/en/blog",
    description: "Node.js project announcements, releases and runtime publications.", topic: "data-infrastructure", tags: ["Node.js", "JavaScript", "runtime", "releases"] },
  { id: "explore:python", name: "Python Documentation", url: "https://docs.python.org/3/",
    description: "Python language and standard library documentation.", topic: "data-infrastructure", tags: ["Python", "runtime", "documentation", "libraries"] },
  { id: "explore:kubernetes", name: "Kubernetes", url: "https://kubernetes.io/blog/",
    description: "Kubernetes project writing about orchestration, operations and releases.", topic: "data-infrastructure", tags: ["Kubernetes", "containers", "operations", "infrastructure"] },
  { id: "explore:docker", name: "Docker", url: "https://www.docker.com/blog/",
    description: "Docker publications on containers, development workflows and infrastructure.", topic: "data-infrastructure", tags: ["Docker", "containers", "development", "infrastructure"] },
  { id: "explore:redis", name: "Redis", url: "https://redis.io/blog/",
    description: "Redis publications on caching, data systems and application engineering.", topic: "data-infrastructure", tags: ["Redis", "caching", "databases", "performance"] },
  { id: "explore:duckdb", name: "DuckDB", url: "https://duckdb.org/news/",
    description: "DuckDB project engineering articles and release announcements.", topic: "data-infrastructure", tags: ["DuckDB", "SQL", "analytics", "data systems"] },
  { id: "explore:clickhouse", name: "ClickHouse", url: "https://clickhouse.com/blog",
    description: "ClickHouse writing on analytical databases, query performance and data engineering.", topic: "data-infrastructure", tags: ["ClickHouse", "SQL", "analytics", "performance"] },
  { id: "explore:grafana", name: "Grafana Labs", url: "https://grafana.com/blog/",
    description: "Grafana Labs publications about observability, metrics and operations.", topic: "data-infrastructure", tags: ["Grafana", "observability", "metrics", "operations"] },
  { id: "explore:prometheus", name: "Prometheus", url: "https://prometheus.io/blog/",
    description: "Prometheus project announcements and monitoring engineering articles.", topic: "data-infrastructure", tags: ["Prometheus", "monitoring", "metrics", "operations"] },
  { id: "explore:tailscale", name: "Tailscale", url: "https://tailscale.com/blog",
    description: "Tailscale writing about networking, security and infrastructure.", topic: "data-infrastructure", tags: ["Tailscale", "networking", "security", "infrastructure"] },
  { id: "explore:github", name: "GitHub Blog", url: "https://github.blog/",
    description: "GitHub engineering, developer tools and software collaboration publications.", topic: "data-infrastructure", tags: ["GitHub", "development", "security", "engineering"] },
  { id: "explore:spotify-engineering", name: "Spotify Engineering", url: "https://engineering.atspotify.com/",
    description: "Spotify engineering writing on software systems, infrastructure and data.", topic: "data-infrastructure", tags: ["engineering", "data systems", "infrastructure", "operations"] },
  { id: "explore:netlify", name: "Netlify", url: "https://www.netlify.com/blog/",
    description: "Netlify publications on web development and deployment workflows.", topic: "data-infrastructure", tags: ["Netlify", "web", "deployment", "development"] },
  { id: "explore:vercel", name: "Vercel", url: "https://vercel.com/blog",
    description: "Vercel writing about web frameworks, deployment and application engineering.", topic: "data-infrastructure", tags: ["Vercel", "Next.js", "web", "deployment"] },
  { id: "explore:supabase", name: "Supabase", url: "https://supabase.com/blog",
    description: "Supabase engineering and product publications about Postgres and application services.", topic: "data-infrastructure", tags: ["Supabase", "PostgreSQL", "databases", "API"] },
  { id: "explore:cloudflare-workers", name: "Cloudflare Workers", url: "https://blog.cloudflare.com/tag/workers/",
    description: "Cloudflare Workers engineering and product publications.", topic: "data-infrastructure", tags: ["Cloudflare", "Workers", "agents", "infrastructure"] },
  { id: "explore:rust", name: "Rust Blog", url: "https://blog.rust-lang.org/",
    description: "Rust project announcements and language engineering publications.", topic: "data-infrastructure", tags: ["Rust", "programming", "runtime", "releases"] },
  { id: "explore:go", name: "The Go Blog", url: "https://go.dev/blog/",
    description: "Go project writing on language features, software engineering and releases.", topic: "data-infrastructure", tags: ["Go", "programming", "runtime", "engineering"] },

  { id: "explore:circle-blog", name: "Circle Blog", url: "https://www.circle.com/blog",
    description: "Circle publications on USDC, payment infrastructure and company announcements.", topic: "payments", tags: ["Circle", "USDC", "Gateway", "payments"] },
  { id: "explore:circle-docs", name: "Circle Developer Docs", url: "https://developers.circle.com/",
    description: "Circle developer documentation for stablecoins, wallets and payment services.", topic: "payments", tags: ["Circle", "USDC", "Gateway", "CCTP", "API"] },
  { id: "explore:arc-docs", name: "Arc Docs", url: "https://docs.arc.network/",
    description: "Arc network documentation for developers.", topic: "payments", tags: ["Arc", "network", "USDC", "documentation"] },
  { id: "explore:stripe-blog", name: "Stripe Blog", url: "https://stripe.com/blog",
    description: "Stripe publications on payment products, engineering and internet businesses.", topic: "payments", tags: ["Stripe", "payments", "engineering", "business"] },
  { id: "explore:stripe-docs", name: "Stripe Documentation", url: "https://docs.stripe.com/",
    description: "Stripe API documentation and payment integration guides.", topic: "payments", tags: ["Stripe", "API", "payments", "idempotency"] },
  { id: "explore:ethereum-docs", name: "Ethereum Developer Docs", url: "https://ethereum.org/en/developers/docs/",
    description: "Ethereum documentation on smart contracts, accounts and development tools.", topic: "payments", tags: ["Ethereum", "contracts", "wallets", "documentation"] },
  { id: "explore:stellar-docs", name: "Stellar Developer Docs", url: "https://developers.stellar.org/",
    description: "Stellar developer documentation for network tools and smart contracts.", topic: "payments", tags: ["Stellar", "contracts", "network", "documentation"] },
  { id: "explore:x402", name: "x402", url: "https://www.x402.org/",
    description: "x402 project information and publications about HTTP payments.", topic: "payments", tags: ["x402", "HTTP", "payments", "agents"] },
  { id: "explore:bis", name: "Bank for International Settlements", url: "https://www.bis.org/",
    description: "BIS research and publications on financial systems, payments and central banking.", topic: "payments", tags: ["BIS", "payments", "research", "financial systems"] },

  { id: "explore:creative-commons", name: "Creative Commons", url: "https://creativecommons.org/blog/",
    description: "Creative Commons publications about open licensing and shared knowledge.", topic: "creator-research", tags: ["licensing", "open access", "creators", "commons"] },
  { id: "explore:datacite", name: "DataCite", url: "https://blog.datacite.org/",
    description: "DataCite publications about research metadata, datasets and persistent identifiers.", topic: "creator-research", tags: ["DOI", "datasets", "metadata", "research"] },
  { id: "explore:crossref", name: "Crossref", url: "https://www.crossref.org/blog/",
    description: "Crossref writing about scholarly metadata, publishing and research infrastructure.", topic: "creator-research", tags: ["DOI", "citations", "metadata", "publishing"] },
  { id: "explore:orcid", name: "ORCID", url: "https://info.orcid.org/",
    description: "ORCID information and publications about researcher identifiers and research records.", topic: "creator-research", tags: ["identifiers", "researchers", "metadata", "publishing"] },
  { id: "explore:doaj", name: "Directory of Open Access Journals", url: "https://blog.doaj.org/",
    description: "DOAJ publications about open access journals and scholarly publishing.", topic: "creator-research", tags: ["open access", "journals", "publishing", "research"] },
  { id: "explore:openalex", name: "OpenAlex", url: "https://blog.openalex.org/",
    description: "OpenAlex publications about open scholarly data and research discovery.", topic: "creator-research", tags: ["scholarly data", "citations", "discovery", "research"] },
  { id: "explore:arxiv", name: "arXiv", url: "https://blog.arxiv.org/",
    description: "arXiv news about preprints, scholarly communication and platform development.", topic: "creator-research", tags: ["preprints", "open access", "publishing", "research"] },
  { id: "explore:zenodo", name: "Zenodo", url: "https://blog.zenodo.org/",
    description: "Zenodo publications about open research repositories and research sharing.", topic: "creator-research", tags: ["repositories", "datasets", "open access", "research"] },
  { id: "explore:wikimedia", name: "Wikimedia Diff", url: "https://diff.wikimedia.org/",
    description: "Wikimedia movement publications about community work and shared knowledge.", topic: "creator-research", tags: ["Wikimedia", "community", "open knowledge", "publishing"] },
  { id: "explore:super-simple-songs", name: "Super Simple Songs", url: "https://www.youtube.com/channel/UCLsooMJoIpl_7ux2jvdPB-Q",
    description: "Publisher channel linked from Super Simple's official channel directory; video metadata is separate from video review.", topic: "creator-research", tags: ["YouTube", "children", "English", "songs", "creator research"] },
];
