[package]
name = "keryx-core"
version = "0.1.0"
edition.workspace = true

[features]
publication-evaluation = []

[[example]]
name = "publish-task-v1"
required-features = ["publication-evaluation"]

[dependencies]
serde_json = { version = "=1.0.145", features = ["preserve_order", "float_roundtrip", "raw_value"] }
serde_core = "=1.0.229"
rustpython-wtf8 = "=0.5.0"
sha2 = "=0.10.9"
ryu-js = "=1.0.3"
cap-std = "=4.0.3"
cap-fs-ext = "=4.0.3"
same-file = "=1.0.6"

[target.'cfg(unix)'.dependencies]
libc = "=0.2.189"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "=0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_Threading", "Win32_System_SystemServices"] }
