const provider = { name: "provider", in: "path", required: true, schema: { type: "string", enum: ["orcid", "github"] } };
const precondition = { name: "X-Keryx-Expected-Wallet", in: "header", required: true, schema: { type: "string", pattern: "^0x[0-9a-fA-F]{40}$" }, description: "Comparison against active SIWE owner; never selects a wallet." };
const failures = { "400": { description: "Invalid request, expired or replayed identity flow." }, "401": { description: "No active authenticated owner." }, "403": { description: "Insufficient explicit profile:read scope, or interactive same-origin SIWE session required." }, "409": { description: "Owner changed, saved profile required, or external identity conflict; no other owner disclosed." }, "503": { description: "Ordinary identity capability, fixed OAuth configuration or provider unavailable. Sealed/enrolled storage refuses; no fallback." } };
const interactive = { security: [{ WebSession: [] }], tags: ["Account"], parameters: [provider, precondition] };
export const profileIdentityOpenApiPaths = {
  "/api/me/profile/identities": { get: { operationId: "readPrivateProfileIdentities", tags: ["Account"], security: [{ WebSession: [] }, { ApiKeyAuth: [] }],
    summary: "Read your private verified external identity links", description: "Active SIWE or explicit profile:read key binds owner. No query/wallet selector or tokens. Strict wallet + at most two identity records(provider,externalId,label,wallet,verifiedAt). Typed profile links remain unverified and the existing private-profile response is unchanged. no-store/no-referrer. Source-only ordinary capability; sealed production activation requires separate reviewed migration/enrollment. Verification never changes login/payment/creator authority.",
    responses: { "200": { description: "Owner-only allowlisted identities, no tokens, pending nonce or other provider profile data." }, ...failures } } },
  "/api/me/profile/identities/{provider}/start": { post: { ...interactive, operationId: "startPrivateIdentityVerification", summary: "Begin interactive ORCID/GitHub verification",
    description: "Body/query-free same-origin POST with owner precondition, active durable SIWE and saved private profile. API keys cannot start OAuth. Fixed configured HTTPS origin/provider URLs. Five-minute encrypted HttpOnly Secure SameSite=Lax purpose-specific cookie; session-bound single-use hashed state in ordinary storage. GitHub empty public scope + S256 PKCE; ORCID /authenticate only. A new flow supersedes old pending work without removing the previous verified link. No wallet/key/provider token is returned.",
    responses: { "200": { description: "authorizationUrl on the fixed provider plus encrypted flow cookie; browser navigates explicitly." }, "428": { description: "Owner comparison header missing." }, ...failures } } },
  "/api/me/profile/identities/{provider}": { delete: { ...interactive, operationId: "unlinkPrivateIdentity", summary: "Remove your verified identity and pending flow",
    description: "Body/query-free owner SIWE + exact Origin. Atomic unlink immediately invalidates pending and consumed in-flight callbacks. Does not revoke a provider account or change research/payment history. Profile deletion also cascades private identity state. No OAuth token is retained for later revocation.",
    responses: { "200": { description: "unlinked:true; idempotent, no removed data echoed." }, "428": { description: "Owner comparison header missing." }, ...failures } } },
  "/api/me/profile/identities/{provider}/callback": { get: { operationId: "completePrivateIdentityVerification", tags: ["Account"], security: [{ WebSession: [] }], parameters: [provider],
    summary: "Provider authorization-code callback", description: "Provider/browser navigation only. Exact configured origin, encrypted provider-bound cookie, matching state and same active SIWE session required. Consume before bounded fixed-endpoint token exchange, recheck active durable session/expiry/current lineage atomically before saving. One external ID per provider can belong to one wallet profile at a time. Tokens/codes/PKCE remain ephemeral. Fixed /me/profile redirect contains only generic status; no redirect selector, provider error, identity or credentials.",
    responses: { "303": { description: "Fixed profile return with generic verified/conflict/failed status and cleared flow cookie, no-store/no-referrer." }, ...failures } } },
};
