const fields = { type: "object", additionalProperties: false, required: ["displayName", "handle", "bio", "purpose", "links"], properties: {
  displayName: { type: "string", maxLength: 80 }, handle: { type: "string", maxLength: 32, description: "Empty clears; otherwise canonical case-insensitive ASCII handle, 3–32 characters, first character a letter. Reserved names refused." },
  bio: { type: "string", maxLength: 160 }, purpose: { type: "string", maxLength: 160 },
  links: { type: "array", maxItems: 6, items: { type: "object", additionalProperties: false, required: ["kind", "url"], properties: { kind: { type: "string", enum: ["orcid", "github", "linkedin", "x", "website", "telegram"] }, url: { type: "string", maxLength: 512, description: "Allowed HTTPS profile/website URL; no credentials, port, query or fragment. No fetching or identity verification." } } } },
} };
const security = [{ WebSession: [] }, { ApiKeyAuth: [] }];
const ownerPrecondition = [{ name: "X-Keryx-Expected-Wallet", in: "header", required: false, schema: { type: "string", pattern: "^0x[0-9a-fA-F]{40}$" }, description: "Required on cookie PUT/DELETE; optional for scoped key writes. Comparison only against the independently authenticated wallet; never selects owner. Mismatch refuses before profile storage." }];
const failures = { "400": { description: "Invalid/bounded profile, malformed owner precondition or forbidden owner selector." }, "401": { description: "Missing/revoked authentication." }, "403": { description: "Required explicit profile scope absent, or cookie mutation Origin is not exactly same-origin." }, "503": { description: "profile_unavailable: ordinary RPC missing/unavailable or enrolled/native domain unsupported. No REST fallback." } };
export const privateProfileOpenApiPaths = { "/api/me/profile": {
  get: { operationId: "readPrivateProfile", tags: ["Account"], summary: "Read your private profile and recorded activity", security,
    description: "Owner comes only from an active SIWE session or verified profile:read API key. No wallet/query selector. Cache-Control:no-store. Private fields never join public queries, receipts, user summaries or streams. Ordinary storage source capability only; current sealed production remains unavailable until its own reviewed migration. Activity covers the whole attributed current store, not anonymous/archive history or independent payer identity; at most 12 recorded topics. creatorsPaid counts distinct valid payee wallets in fetch/citation events with positive amount, exact selected network, settled=true, settlement_status=settled and nonempty recorded transfer ID. No independent Circle reconciliation.",
    responses: { "200": { description: "Owner profile (or null) and derived activity, with provenance scope/network." }, ...failures } },
  put: { operationId: "replacePrivateProfile", tags: ["Account"], summary: "Replace your private profile fields", security, parameters: ownerPrecondition,
    description: "Active SIWE plus exact same-origin Origin and owner precondition, or explicit profile:write key (optional comparison-only precondition). 8192-byte JSON/5-second body cap. Text is bounded plain single-line data. Atomic case-insensitive handle uniqueness; one link per kind. Write does not imply read: acknowledgement returns only replacement fields/server timestamps, no prior profile/activity. No payment, grants, authorizations, source or account identity changes.",
    requestBody: { required: true, content: { "application/json": { schema: fields } } }, responses: { "200": { description: "Submitted replacement profile plus wallet and timestamps." }, "409": { description: "handle_conflict or profile_owner_changed without exposing another owner." }, "428": { description: "Missing cookie owner precondition." }, ...failures } },
  delete: { operationId: "deletePrivateProfile", tags: ["Account"], summary: "Delete your private fields and links", security, parameters: ownerPrecondition,
    description: "Same authentication/Origin/precondition rules as PUT. Idempotent owner-only deletion; handle becomes available. Research, account, payment, settlement and original authorization history are retained unchanged.", responses: { "200": { description: "deleted:true; no deleted private data echoed." }, "409": { description: "profile_owner_changed without exposing another owner." }, "428": { description: "Missing cookie owner precondition." }, ...failures } },
} };
